[default_session]
startup_command = "nvim -c ':Telescope find_files'"
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "desktop"
path = "~/Desktop"
startup_command = "yazi"

[[session]]
name = "dotfiles"
path = "~/Code/tnez/dotfiles"

[[session]]
name = "downloads"
path = "~/Downloads"
startup_command = "yazi"

[[session]]
name = "org"
path = "~/Code/tnez/tnez.dev/org"

[[scoutos]]
name = "scoutos"
path = "~/Code/scoutos/scoutos/main"

[[tnezdev]]
name = "tnezdev"
path = "~/Code/tnez/tnez.dev"
