[[session]]
name = "Desktop"
path = "~/Desktop"
startup_command = "yazi"

[[session]]
name = "Downloads"
path = "~/Downloads"
startup_command = "yazi"

[[session]]
name = "Today"
path = "~/Code/tnez/things.tnez.dev"
startup_command = "nvim inbox/daily-notes--$(date +%F).md"

[[session]]
name = "Yesterday"
path = "~/Code/tnez/things.tnez.dev"
startup_command = "nvim inbox/daily-notes--$(date -v-1d +%F).md"

[[session]]
name = "Tomorrow"
path = "~/Code/tnez/things.tnez.dev"
startup_command = "nvim inbox/daily-notes--$(date -v+1d +%F).md"
